spring:
  application:
    name: step07_CICD

server:
  port: 81

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,metrics"
  prometheus:
    metrics:
      export:
        enabled: true